version: "3.8"
services:
    mongodb:
        image: mongo
        container_name: AudioBooks
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: 123456
        volumes:
            - mongodb-data:/data/db

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        ports:
            - "8888:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
            ME_CONFIG_MONGODB_SERVER: AudioBooks
            ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
            ME_CONFIG_BASICAUTH_USERNAME: user
            ME_CONFIG_BASICAUTH_PASSWORD: 123456
        depends_on:
            - mongodb

volumes:
    mongodb-data:
